version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Redirige le port 80 du conteneur vers le port 8080 de l'hôte
    restart: always

